### PR TITLE
Implementation of event cards other event times in front page.

### PR DESCRIPTION
**Pull request by nikomakela**
PT-1050 PT-1107.

NOTE: This needs new API https://github.com/City-of-Helsinki/palvelutarjotin/pull/191

### CODE REVIEW

**Comment by nikomakela** [comment]
NOTE: Tests fails because API is not published yet

**Comment by nikomakela** [comment]
The API changes are now merged and live! It seems like the loading indicator is too big 😞 . @Sartonon any ideas how to fix it?

**Review by Sartonon — COMMENTED** [review]
Looks good! Couple comments

**Review by Sartonon — APPROVED** [review]
Great!

**Pull request merged**
