### PR TITLE
PT-1606 | fix: update banner hero texts and raise search box a bit

### PR DESCRIPTION
**Pull request by karisal-anders**
### fix: update banner hero texts and raise search box a bit

refs PT-1606

### Closes :no_good_woman:

**[PT-1606](https://helsinkisolutionoffice.atlassian.net/browse/PT-1606)**

## Additional notes :spiral_notepad:

[PT-1606]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**kultus-ui branch is deployed to platta: https://kultus-ui-pr274.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-ui branch is deployed to platta: https://kultus-ui-pr274.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-ui branch is deployed to platta: https://kultus-ui-pr274.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-ui branch is deployed to platta: https://kultus-ui-pr274.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-ui branch is deployed to platta: https://kultus-ui-pr274.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-ui branch is deployed to platta: https://kultus-ui-pr274.dev.hel.ninja** :rocket::rocket::rocket:

**Review by HeikkM — APPROVED** [review]

**Pull request merged**
