### PR TITLE
PT-1720 | Refactoring & cleaning up

### PR DESCRIPTION
**Pull request by karisal-anders**
### refactor: use HDS v3.7's breakpoints directly if possible

old breakpoint name (old breakpoint width) / new name (new width):
 - sm (768px) -> m (768px) = $breakpoint-m in HDS v3.7
 - md (992px) -> l (992px) = $breakpoint-l in HDS v3.7
 - xlg (1600px) -> xxl (1600px), a custom breakpoint, not in HDS v3.7

refs PT-1720 (cleaning up / refactoring after the fact)

### refactor: make queryToString function faster, conciser & more readable

refs PT-1720 (cleaning up / refactoring)

### refactor: remove header stylings as unnecessary (no need with HDS v3.7)

refs PT-1720 (cleanup / refactoring after the fact)

### Related :handshake:

[PT-1720](https://helsinkisolutionoffice.atlassian.net/browse/PT-1720)
https://github.com/City-of-Helsinki/palvelutarjotin-ui/pull/304

## Additional notes :spiral_notepad:

[PT-1720]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**kultus-ui branch is deployed to platta: https://kultus-ui-pr316.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
TODO:
 - [ ] Update snapshots

**Comment by terovirtanen** [comment]
**kultus-ui branch is deployed to platta: https://kultus-ui-pr316.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
@nikomakela @melniiv @jakezu This is now ready for code review, the rollouts are failing but there's a [service portal ticket](https://helsinkisolutionoffice.atlassian.net/servicedesk/customer/portal/3/PSD-2536?created=true) for that which you should be able to see.

**Comment by nikomakela** [comment]
> @nikomakela @melniiv @jakezu This is now ready for code review, the rollouts are failing but there's a [service portal ticket](https://helsinkisolutionoffice.atlassian.net/servicedesk/customer/portal/3/PSD-2536?created=true) for that which you should be able to see.

Is the readiness probe checked from the wrong path (again)?

**Review by melniiv — APPROVED** [review]

**Pull request merged**
