### PR TITLE
PT-1732 | fix: event hero background

### PR DESCRIPTION
**Pull request by melniiv**
## Description :sparkles:
Show hero image as div background and remove the img tag

### Closes :no_good_woman:

**[PT-1732](https://helsinkisolutionoffice.atlassian.net/browse/PT-1732):**

## Additional notes :spiral_notepad:

[PT-1732]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**kultus-ui branch is deployed to platta: https://kultus-ui-pr313.dev.hel.ninja** :rocket::rocket::rocket:

**Review by nikomakela — COMMENTED** [review]
Where is the alt text of the image now? Isn't it quite mandatory?

**Comment by melniiv** [comment]
ok, made a fix with css only

**Comment by terovirtanen** [comment]
**kultus-ui branch is deployed to platta: https://kultus-ui-pr313.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
