### PR TITLE
PT-1606 | fix: fix banner hero layout accessibility issue 4.1

### PR DESCRIPTION
**Pull request by karisal-anders**
### fix: fix banner hero layout accessibility issue 4.1

refs PT-1606

### Closes :no_good_woman:

**[PT-1606](https://helsinkisolutionoffice.atlassian.net/browse/PT-1606)**

## Additional notes :spiral_notepad:

[PT-1606]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**kultus-ui branch is deployed to platta: https://kultus-ui-pr273.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**kultus-ui branch is deployed to platta: https://kultus-ui-pr273.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by karisal-anders** [comment]
The designer gave his approval for this layoutwise in a private message to me.

**Comment by karisal-anders** [comment]
Please could one of you code review this @PekkaKela, @HeikkM or @jannetalvio? Thank you! We can also have a live session if needed, in that case ping me on Slack.

**Review by HeikkM — APPROVED** [review]

**Pull request merged**
